In [1]:
import pandas as pd
import numpy as np
from datetime import datetime as dt
import numpy as np

In [2]:
beers=pd.read_csv("../../data/beer.gz")
beers.head()

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

In [3]:
beers=pd.DataFrame(beers.groupby(["brewery_id","brewery_name","beer_beerid","beer_name","beer_style"]).agg(
    {"beer_abv":"mean",
     "review_overall":"mean",
     "review_aroma":"mean",
     "review_appearance":"mean",
     "review_palate":"mean",
     "review_taste":"mean"}))
beers=beers.reset_index(drop=False)

In [4]:
words=pd.read_csv("reviews.csv")
words=words.drop(["brewery_id","review_overall"],axis=1)
beers=beers.merge(words,on="beer_beerid")
beers.columns

Index(['brewery_id', 'brewery_name', 'beer_beerid', 'beer_name', 'beer_style',
       'beer_abv', 'review_overall', 'review_aroma', 'review_appearance',
       'review_palate',
       ...
       'bubbly', 'gentle', 'carbonation', 'full', 'light', 'slick', 'heavy',
       'dry', 'thick', 'thin'],
      dtype='object', length=188)

In [5]:
brewery=beers[["brewery_id","brewery_name"]]
brewery=brewery.drop_duplicates(subset=["brewery_id"],keep='first')
brewery.columns=["id","name"]
brewery.head()
#brewery.to_csv("../database/brewery.csv",index=False)

     id                                    name
0     1                Plzensky Prazdroj, a. s.
13    3                       Abita Brewing Co.
52    4                Allagash Brewing Company
111   5  Yakima Brewing Co. / Bert Grant's Ales
119   6                  Brouwerij Slaghmuylder

In [7]:
beer_style=pd.DataFrame({"style":beers["beer_style"].unique()})
beer_style.head()
#beer_style.to_csv("../database/beer_style.csv",index=False)

               style
0     Czech Pilsener
1  Euro Strong Lager
2      Baltic Porter
3       Vienna Lager
4  English Brown Ale

In [8]:
for i in beers.columns:
    print(i)

brewery_id
brewery_name
beer_beerid
beer_name
beer_style
beer_abv
review_overall
review_aroma
review_appearance
review_palate
review_taste
word
malty
grainy
sweet
corn-like
hay
straw
cracker
bicuity
caramel
toast
roast
coffee
espresso
burnt
alcohol
tobacco
gunpowder
leather
pine
grass
raisins
currant
plum
dates
prunes
figs
blackberry
blueberry
banana
pineapple
apricot
pear
apple
nectarine
peach
mango
lemon
lime
orange
tangerine
clementine
grapefruit
zest
metallic
vinegar
copper
cidery
astringent
chlorine
phenolic
pepper
clove
anise
licorice
bacon
fatty
nutty
butterscotch
vanilla
earthy
woody
bread
saddle
musty
barnyard
honey
chestnut
black
garnet
ruby
brilliant
hazy
cloudy
turbid
opaque
clear
crystal
bright
dull
persistent
rocky
large
fluffy
dissipating
lingering
white
tan
frothy
delicate
roasted
bready
bitter
spicy
fruity
chocolate
toffee
tart
subtle
woodsy
sulfuric
assertive
mild
bold
balanced
robust
intense
harsh
complex
refined
hearty
smooth
silky
velvety
prickly
tingly
creamy
warming
viscous
oily
Malty
biscuity
breadlike
rich
deep
roasty
cereal
cookie
coffeeish
caramelly
molasses
complexity
smoky
autumnal
cream
milk
oatmeal
rustic
layered
piney
citrusy
grapefruity
sharp
fresh
herbal
zippy
lemony
aromatic
floral
springlike
sprucelike
juniper
minty
pungent
elegant
grassy
baked
bubblegum
yeasty
belgian
tropical
clean
soft
effervescent
spritzy
sparkling
pinpoint
bubbly
gentle
carbonation
full
light
slick
heavy
dry
thick
thin

In [12]:
beer=beers.drop(["brewery_name","word"],axis=1)
beer=beer.drop_duplicates(subset=["beer_beerid"],keep='first')
beer.head()
#beer.to_csv("../database/beer.csv",index=False)

,brewery_id,beer_beerid,beer_name,beer_style,beer_abv,review_overall,review_aroma,review_appearance,review_palate,review_taste,...,bubbly,gentle,carbonation,full,light,slick,heavy,dry,thick,thin
0,1,429,Pilsner Urquell,Czech Pilsener,4.4,3.830549,3.445107,3.694909,3.642403,3.660302,...,0,0,9,1,15,0,1,3,1,1
1,1,5916,Gambrinus,Czech Pilsener,5.0,3.750000,3.282609,3.532609,3.347826,3.467391,...,0,0,22,2,23,0,1,5,4,2
2,1,14348,Eisbrau Czech,Czech Pilsener,5.0,3.750000,3.333333,3.500000,3.500000,3.583333,...,0,0,1,3,2,0,1,0,0,2
3,1,19099,Primus,Czech Pilsener,4.2,3.125000,2.375000,3.000000,3.125000,2.625000,...,0,0,4,0,5,0,0,0,0,1
4,1,19123,Gambrinus Pale,Czech Pilsener,4.1,3.928571,3.357143,3.285714,3.571429,3.357143,...,0,0,2,0,3,0,1,1,3,2